export const WASTE_TYPES = [
  { label: 'E-Waste', value: 'E-Waste', color: 'purple' },
  { label: 'Bio-Medical Waste', value: 'Bio-Medical Waste', color: 'volcano' },
  { label: 'Plastic Waste Management', value: 'Plastic Waste Management', color: 'cyan' },
];

export const TN_DISTRICTS = [
  'Ariyalur',
  'Chengalpattu',
  'Chennai',
  'Coimbatore',
  'Cuddalore',
  'Dharmapuri',
  'Dindigul',
  'Erode',
  'Kallakurichi',
  'Kanchipuram',
  'Kanyakumari',
  'Karur',
  'Krishnagiri',
  'Madurai',
  'Mayiladuthurai',
  'Nagapattinam',
  'Namakkal',
  'Nilgiris',
  'Perambalur',
  'Pudukkottai',
  'Ramanathapuram',
  'Ranipet',
  'Salem',
  'Sivaganga',
  'Tenkasi',
  'Thanjavur',
  'Theni',
  'Thoothukudi',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupathur',
  'Tiruppur',
  'Tiruvallur',
  'Tiruvannamalai',
  'Tiruvarur',
  'Vellore',
  'Viluppuram',
  'Virudhunagar',
];

export const REPORT_STATUSES = {
  PENDING: { label: 'Pending Verification', color: 'gold' },
  VERIFIED: { label: 'Verified', color: 'success' },
  REVISION_REQUESTED: { label: 'Revision Required', color: 'error' },
};
